# import libraries

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import StandardScaler, PolynomialFeatures

# Preparing and Understanding the data

In [3]:
df=pd.read_csv("vehicles.csv") 
df

id                                                url  \
0       7222695916  https://prescott.craigslist.org/cto/d/prescott...   
1       7218891961  https://fayar.craigslist.org/ctd/d/bentonville...   
2       7221797935  https://keys.craigslist.org/cto/d/summerland-k...   
3       7222270760  https://worcester.craigslist.org/cto/d/west-br...   
4       7210384030  https://greensboro.craigslist.org/cto/d/trinit...   
...            ...                                                ...   
426875  7301591192  https://wyoming.craigslist.org/ctd/d/atlanta-2...   
426876  7301591187  https://wyoming.craigslist.org/ctd/d/atlanta-2...   
426877  7301591147  https://wyoming.craigslist.org/ctd/d/atlanta-2...   
426878  7301591140  https://wyoming.craigslist.org/ctd/d/atlanta-2...   
426879  7301591129  https://wyoming.craigslist.org/ctd/d/atlanta-2...   

                        region                         region_url  price  \
0                     prescott    https://prescott.craigslist.org   6000   
1                 fayetteville       https://fayar.craigslist.org  11900   
2                 florida keys        https://keys.craigslist.org  21000   
3       worcester / central MA   https://worcester.craigslist.org   1500   
4                   greensboro  https://greensboro.craigslist.org   4900   
...                        ...                                ...    ...   
426875                 wyoming     https://wyoming.craigslist.org  23590   
426876                 wyoming     https://wyoming.craigslist.org  30590   
426877                 wyoming     https://wyoming.craigslist.org  34990   
426878                 wyoming     https://wyoming.craigslist.org  28990   
426879                 wyoming     https://wyoming.craigslist.org  30590   

          year manufacturer                     model condition    cylinders  \
0          NaN          NaN                       NaN       NaN          NaN   
1          NaN          NaN                       NaN       NaN          NaN   
2          NaN          NaN                       NaN       NaN          NaN   
3          NaN          NaN                       NaN       NaN          NaN   
4          NaN          NaN                       NaN       NaN          NaN   
...        ...          ...                       ...       ...          ...   
426875  2019.0       nissan         maxima s sedan 4d      good  6 cylinders   
426876  2020.0        volvo  s60 t5 momentum sedan 4d      good          NaN   
426877  2020.0     cadillac          xt4 sport suv 4d      good          NaN   
426878  2018.0        lexus           es 350 sedan 4d      good  6 cylinders   
426879  2019.0          bmw  4 series 430i gran coupe      good          NaN   

        ... size       type paint_color  \
0       ...  NaN        NaN         NaN   
1       ...  NaN        NaN         NaN   
2       ...  NaN        NaN         NaN   
3       ...  NaN        NaN         NaN   
4       ...  NaN        NaN         NaN   
...     ...  ...        ...         ...   
426875  ...  NaN      sedan         NaN   
426876  ...  NaN      sedan         red   
426877  ...  NaN  hatchback       white   
426878  ...  NaN      sedan      silver   
426879  ...  NaN      coupe         NaN   

                                                image_url  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
426875  https://images.craigslist.org/00o0o_iiraFnHg8q...   
426876  https://images.craigslist.org/00x0x_15sbgnxCIS...   
426877  https://images.craigslist.org/00L0L_farM7bxnxR...   
426878  https://images.craigslist.org/00z0z_bKnIVGLkDT...   
426879  https://images.craigslist.org/00Y0Y_lEUocjyRxa...   

               

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            426880 non-null  int64  
 1   url           426880 non-null  object 
 2   region        426880 non-null  object 
 3   region_url    426880 non-null  object 
 4   price         426880 non-null  int64  
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object 
 7   model         421603 non-null  object 
 8   condition     252776 non-null  object 
 9   cylinders     249202 non-null  object 
 10  fuel          423867 non-null  object 
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object 
 13  transmission  424324 non-null  object 
 14  VIN           265838 non-null  object 
 15  drive         296313 non-null  object 
 16  size          120519 non-null  object 
 17  type          334022 non-null  object 
 18  pain

In [7]:
df.sample(10, random_state=100)

id                                                url  \
386556  7310167837  https://stgeorge.craigslist.org/ctd/d/salt-lak...   
48650   7316539496  https://reno.craigslist.org/ctd/d/sacramento-2...   
373265  7304670264  https://elpaso.craigslist.org/ctd/d/el-paso-19...   
135832  7316937484  https://spokane.craigslist.org/ctd/d/coeur-ale...   
421385  7306708288  https://madison.craigslist.org/ctd/d/madison-2...   
191837  7316270083  https://worcester.craigslist.org/ctd/d/rochdal...   
126048  7304217087  https://macon.craigslist.org/ctd/d/macon-2019-...   
49936   7313235399  https://reno.craigslist.org/ctd/d/atlanta-2015...   
221323  7310333889  https://semo.craigslist.org/ctd/d/park-hills-2...   
171159  7316005187  https://lexington.craigslist.org/cto/d/berea-2...   

                         region                        region_url  price  \
386556                st george   https://stgeorge.craigslist.org   8550   
48650              reno / tahoe       https://reno.craigslist.org      0   
373265                  el paso     https://elpaso.craigslist.org   8800   
135832  spokane / coeur d'alene    https://spokane.craigslist.org   5277   
421385                  madison    https://madison.craigslist.org  34590   
191837   worcester / central MA  https://worcester.craigslist.org   7900   
126048    macon / warner robins      https://macon.craigslist.org  25590   
49936              reno / tahoe       https://reno.craigslist.org  17990   
221323       southeast missouri       https://semo.craigslist.org  29977   
171159                lexington  https://lexington.craigslist.org   8900   

          year manufacturer                       model  condition  \
386556  2013.0       toyota                      sienna        NaN   
48650   2015.0         ford            f-550 f550 f 550  excellent   
373265  1999.0    chevrolet                    corvette        NaN   
135832  2007.0       subaru        outback 2.5i limited   like new   
421385  2018.0        dodge    durango gt sport utility       good   
191837  2006.0       toyota                rav4 limited  excellent   
126048  2019.0          gmc  acadia sle-1 sport utility       good   
49936   2015.0   volkswagen                golf tdi sel       good   
221323  2000.0    chevrolet                    corvette        NaN   
171159  2010.0       toyota                        rav4        NaN   

           cylinders  ...       size   type paint_color  \
386556   6 cylinders  ...        NaN    van      silver   
48650   10 cylinders  ...  full-size  truck       white   
373265           NaN  ...        NaN  coupe      silver   
135832   4 cylinders  ...   mid-size  wagon      custom   
421385   6 cylinders  ...        NaN    SUV        blue   
191837   4 cylinders  ...   mid-size    SUV       brown   
126048           NaN  ...        NaN    SUV       black   
49936            NaN  ...        NaN  sedan       white   
221323   8 cylinders  ...        NaN  coupe      silver   
171159   4 cylinders  ...        NaN    NaN       white   

                                                image_url  \
386556  https://images.craigslist.org/00r0r_gjqHwSh3WB...   
48650   https://images.craigslist.org/00909_99KdbM2Z2e...   
373265  https://images.craigslist.org/00A0A_3vakBK4mjQ...   
135832  https://images.craigslist.org/00c0c_eiSpRTtgn0...   
421385  https://images.craigslist.org/00N0N_1xMPvfxRAI...   
191837  https://images.craigslist.org/01010_jxcC14bmMD...   
126048  https://images.craigslist.org/00l0l_2gNZhcpqfn...   
49936   https://images.craigslist.org/00000_KNY0kE0TqA...   
221323  https://images.craigslist.org/00p0p_gJP2rR3R6Q...   
171159  https://images.craigslist.org/00P0P_kme70OkdfY...   

                                              description county state  \
386556  Engine: 6 Cylinders Transmission: Automatic Ti...    NaN    ut   
48650   MONTHLY PUBLIC AUCTION SATURDAY – MAY 8th, 202...    NaN    ca   
373265  1999 Chevrolet, Chevy Corvette Hardtop ☎ 915-2...   

In [8]:
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='object')

In [9]:
df.shape

(426880, 26)

In [10]:
df.describe()



id         price           year      odometer  county  \
count  4.268800e+05  4.268800e+05  425675.000000  4.224800e+05     0.0   
mean   7.311487e+09  7.519903e+04    2011.235191  9.804333e+04     NaN   
std    4.473170e+06  1.218228e+07       9.452120  2.138815e+05     NaN   
min    7.207408e+09  0.000000e+00    1900.000000  0.000000e+00     NaN   
25%    7.308143e+09  5.900000e+03    2008.000000  3.770400e+04     NaN   
50%    7.312621e+09  1.395000e+04    2013.000000  8.554800e+04     NaN   
75%    7.315254e+09  2.648575e+04    2017.000000  1.335425e+05     NaN   
max    7.317101e+09  3.736929e+09    2022.000000  1.000000e+07     NaN   

                 lat           long  
count  420331.000000  420331.000000  
mean       38.493940     -94.748599  
std         5.841533      18.365462  
min       -84.122245    -159.827728  
25%        34.601900    -111.939847  
50%        39.150100     -88.432600  
75%        42.398900     -80.832039  
max        82.390818     173.885502

In [11]:
df.year.unique()

array([  nan, 2014., 2010., 2020., 2017., 2013., 2012., 2016., 2019.,
       2011., 1992., 2018., 2004., 2015., 2001., 2006., 1968., 2003.,
       2008., 2007., 2005., 1966., 2009., 1998., 2002., 1999., 2021.,
       1997., 1976., 1969., 1995., 1978., 1954., 1979., 1970., 1974.,
       1996., 1987., 2000., 1955., 1960., 1991., 1972., 1988., 1994.,
       1929., 1984., 1986., 1989., 1973., 1946., 1933., 1958., 1937.,
       1985., 1957., 1953., 1942., 1963., 1977., 1993., 1903., 1990.,
       1965., 1982., 1948., 1983., 1936., 1932., 1951., 1931., 1980.,
       1967., 1971., 1947., 1981., 1926., 1962., 1975., 1964., 1934.,
       1952., 1940., 1959., 1950., 1930., 1956., 1922., 1928., 2022.,
       1901., 1941., 1924., 1927., 1939., 1923., 1949., 1961., 1935.,
       1918., 1900., 1938., 1913., 1916., 1943., 1925., 1921., 1915.,
       1945., 1902., 1905., 1920., 1944., 1910., 1909.])

In [12]:
df.manufacturer.unique()

array([nan, 'gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'acura', 'hyundai', 'mercedes-benz', 'bmw', 'mitsubishi',
       'volkswagen', 'porsche', 'kia', 'rover', 'ferrari', 'mini',
       'pontiac', 'fiat', 'tesla', 'saturn', 'mercury', 'harley-davidson',
       'datsun', 'aston-martin', 'land rover', 'morgan'], dtype=object)

In [13]:
df.cylinders.unique()

array([nan, '8 cylinders', '6 cylinders', '4 cylinders', '5 cylinders',
       'other', '3 cylinders', '10 cylinders', '12 cylinders'],
      dtype=object)

In [14]:
df.paint_color.unique()

array([nan, 'white', 'blue', 'red', 'black', 'silver', 'grey', 'brown',
       'yellow', 'orange', 'green', 'custom', 'purple'], dtype=object)

In [15]:
df.corr()

id     price      year  odometer  county       lat      long
id        1.000000 -0.002779 -0.059040  0.010721     NaN -0.069388 -0.121864
price    -0.002779  1.000000 -0.004925  0.010032     NaN  0.000357 -0.000408
year     -0.059040 -0.004925  1.000000 -0.157215     NaN -0.014677 -0.001410
odometer  0.010721  0.010032 -0.157215  1.000000     NaN -0.001459  0.009807
county         NaN       NaN       NaN       NaN     NaN       NaN       NaN
lat      -0.069388  0.000357 -0.014677 -0.001459     NaN  1.000000 -0.128088
long     -0.121864 -0.000408 -0.001410  0.009807     NaN -0.128088  1.000000

# Split data 


In [4]:
df_train,df_test=train_test_split(df,test_size=0.2 , random_state=0)

In [5]:
df_train,df_val=train_test_split(df_train,test_size=0.25, random_state=100)